### ISSUE TITLE
Publish a new nuget built with v142 (VS 2019)

### ISSUE THREAD

**Issue by stecrain** [microsoft/ChakraCore-Debugger#77]
I just upgraded to Visual Studio 2019. 
I still need to use v141 of the platform toolset though since ChakraCore.Debugger.ProtocolHandler.lib was built with v141

**Comment by JunielKatarn** [comment]
Is this still needed?
It has been established that the main consumer of ChakraCore Debugger also builds using toolset v141.

**Comment by stecrain** [comment]
not needed anymore. I will be trying to move off chakra core and onto hermes.
In the interim i just built chakra core debugger from source
